### ISSUE TITLE
error in running main.py -h

### ISSUE THREAD

**Issue by johnfelipe** [CodeNameGhost/shiva#2]
root@testdos2018:~/shiva# python3
	Python 3.4.3 (default, Nov 28 2017, 16:41:13)
	[GCC 4.8.4] on linux
	Type "help", "copyright", "credits" or "license" for more information.
	>>>
	root@testdos2018:~/shiva# ls
	LICENSE  main.py  proof of work  README.md  savitr  thirdparty
	root@testdos2018:~/shiva# sudo python3 main.py -h
	Traceback (most recent call last):
	  File "main.py", line 8, in <module>
		from savitr.zeus import udp_strike, syn_strike
	  File "/root/shiva/savitr/zeus.py", line 8
		async def udp_strike(**kwargs):
				^
	SyntaxError: invalid syntax

how solved?

**Comment by CodeNameGhost** [comment]
Run `python3 main.py -h`

**Comment by johnfelipe** [comment]
![how](https://user-images.githubusercontent.com/428820/37682765-6b5eb012-2c58-11e8-9a0f-94dd4c46be62.png)
that is command i put in sudo, then u tell me put without sudo?

**Comment by johnfelipe** [comment]
# cd shiva
	/shiva# chmod +x main.py
	/shiva# sudo python3 main.py -h
	Traceback (most recent call last):
	  File "main.py", line 7, in <module>
		from savitr.zeus import *
	  File "/root/shiva/savitr/zeus.py", line 8
		async def udp_strike(**kwargs):
				^
	SyntaxError: invalid syntax
	/shiva# python3 main.py -h
	Traceback (most recent call last):
	  File "main.py", line 7, in <module>
		from savitr.zeus import *
	  File "/root/shiva/savitr/zeus.py", line 8
		async def udp_strike(**kwargs):
				^
	SyntaxError: invalid syntax
	/shiva# ls
	LICENSE  main.py  proof of work  README.md  savitr  thirdparty
	/shiva# python3 main.py
	Traceback (most recent call last):
	  File "main.py", line 7, in <module>
		from savitr.zeus import *
	  File "/root/shiva/savitr/zeus.py", line 8
		async def udp_strike(**kwargs):
				^
	SyntaxError: invalid syntax

nothing works

**Comment by CodeNameGhost** [comment]
It's an import error in main.py. the issue is fixed, try downloading the script again.
